services:
  api:
    image: node:20-alpine
    container_name: horseportal_api
    working_dir: /app
    restart: always
    ports:
      - "127.0.0.1:8085:8085"
    env_file:
      - .env
    volumes:
      - ./:/app
    command: ["node","src/server.js"]
    environment:
      - DATABASE_URL=postgresql://admin:lotidrosaparole11-119@postgres:5432/zirguportals_dev
    networks:
      - infra_default

networks:
  infra_default:
    external: true
